import { describe, expect, test } from "vitest";
import {
  buildGuardedExportAudit,
  buildRawEvidenceSession,
  mappingStageGate,
  promoteMapping,
  validateRoundTrip,
} from "../src/bridge/guardedTransfer";
import { createDefaultBridgeMappings } from "../src/bridge/model";
import type { RawEvidenceSession } from "../src/bridge/types";
import { createPlannedSegment, createPlannedShow } from "../src/planner/model";
import type { TewResearchSnapshot, TewSnapshot } from "../src/tew/types";
import { buildTransferPackage, buildTransferText, synchronizeTransferRecord } from "../src/transfer/model";

function configuredShow() {
  const show = createPlannedShow(1);
  show.name = "PWL Test Night";
  show.date = "2026-08-15";
  show.company = "PWL";
  show.venue = "Civic Arena";
  const match = createPlannedSegment("match");
  match.title = "Jay White vs PAC";
  match.durationMinutes = 18;
  match.workers = [
    { id: "worker-1", name: "Jay White", role: "Competitor", side: "Side 1", source: "tew" },
    { id: "worker-2", name: "PAC", role: "Competitor", side: "Side 2", source: "tew" },
  ];
  match.plannedWinner = "Jay White";
  match.plannedFinish = "Pinfall after Blade Runner";
  match.matchStory = "PAC controls the pace before White creates the decisive opening.";
  match.matchApproachSetup.matchAimId = "storytelling-match";
  match.matchApproachSetup.workerPlans = [
    { workerKey: "tew:worker-1", workerName: "Jay White", selectedApproachIds: ["psychological-manipulator", "opportunistic-schemer", "big-match-performer"], lockedApproachIds: [], mode: "AI", generatedAt: "2026-08-01T00:00:00.000Z" },
    { workerKey: "tew:worker-2", workerName: "PAC", selectedApproachIds: ["aerial-showstopper", "high-tempo-hybrid", "resilient-underdog"], lockedApproachIds: [], mode: "AI", generatedAt: "2026-08-01T00:00:00.000Z" },
  ];
  const angle = createPlannedSegment("angle");
  angle.title = "Post-Match Confrontation";
  angle.segmentOutput = "The next challenger confronts the winner without physical contact.";
  angle.workers = [{ id: "worker-3", name: "Eddie Kingston", role: "Challenger", side: "", source: "tew" }];
  show.segments = [match, angle];
  return show;
}

function researchSnapshot(fileName: string, rows: Array<Record<string, string>>): TewResearchSnapshot {
  return {
    fileName,
    importedAt: "2026-08-01T00:00:00.000Z",
    rowLimit: 500,
    warnings: [],
    tables: [{ name: "tblBooking", columns: ["BookingID", "Name", "Duration"], rowCount: rows.length, sampledRows: rows.length, identityCandidates: ["BookingID"], truncated: false, rows }],
  };
}

function evidenceSession(id: string): RawEvidenceSession {
  return {
    id,
    comparisonReportId: "comparison-1",
    createdAt: "2026-08-01T00:00:00.000Z",
    beforeFileName: `before-${id}.mdb`,
    afterFileName: `after-${id}.mdb`,
    selectedTables: ["tblBooking"],
    identityFields: { tblBooking: "BookingID" },
    tableEvidence: [{
      tableName: "tblBooking",
      identityField: "BookingID",
      beforeRowCount: 0,
      afterRowCount: 1,
      sampledBeforeRows: 0,
      sampledAfterRows: 1,
      insertedCount: 1,
      removedCount: 0,
      changedCount: 0,
      autoGeneratedFields: ["BookingID"],
      rowChanges: [{ tableName: "tblBooking", identityField: "BookingID", identityValue: "1", changeType: "Inserted", fieldChanges: [], beforeRow: null, afterRow: { BookingID: "1", Name: "PWL Test Night", Duration: "120" } }],
      notes: "Rows matched by BookingID.",
    }],
    conclusion: "One table changed.",
  };
}

describe("Phase 5B guarded TEW transfer", () => {
  test("translates matches approaches and angles into TEW entry order", () => {
    const show = configuredShow();
    const pkg = buildTransferPackage(show, createDefaultBridgeMappings());
    expect(pkg.eventFields.map((field) => field.label)).toContain("Show name");
    expect(pkg.segments).toHaveLength(2);
    expect(pkg.segments[0].completeEntryText).toContain("Jay White vs PAC");
    expect(pkg.segments[0].completeEntryText).toContain("Psychological Manipulator");
    expect(pkg.segments[0].completeEntryText).toContain("PAC controls the pace");
    expect(pkg.segments[1].completeEntryText).toContain("Post-Match Confrontation");
    expect(buildTransferText(pkg)).toContain("does not modify a TEW database");
  });

  test("preserves transfer progress when a package is regenerated", () => {
    const show = configuredShow();
    const first = buildTransferPackage(show, createDefaultBridgeMappings());
    const record = synchronizeTransferRecord(undefined, first);
    record.eventProgress[0].status = "Entered";
    record.segmentProgress[0].fields[0].status = "Copied";
    const second = buildTransferPackage(show, createDefaultBridgeMappings());
    const updated = synchronizeTransferRecord(record, second);
    expect(updated.packageHistory).toHaveLength(2);
    expect(updated.eventProgress[0].status).toBe("Entered");
    expect(updated.segmentProgress[0].fields[0].status).toBe("Copied");
  });

  test("compares selected raw rows using a confirmed identity field", () => {
    const before = researchSnapshot("before.mdb", [{ BookingID: "1", Name: "Old Show", Duration: "90" }]);
    const after = researchSnapshot("after.mdb", [
      { BookingID: "1", Name: "Old Show", Duration: "120" },
      { BookingID: "2", Name: "PWL Test Night", Duration: "120" },
    ]);
    const session = buildRawEvidenceSession("comparison-1", before, after, ["tblBooking"], { tblBooking: "BookingID" });
    expect(session.tableEvidence[0].insertedCount).toBe(1);
    expect(session.tableEvidence[0].changedCount).toBe(1);
    expect(session.tableEvidence[0].rowChanges.find((row) => row.identityValue === "1")?.fieldChanges[0]).toMatchObject({ field: "Duration", beforeValue: "90", afterValue: "120" });
  });

  test("requires repeated evidence and documented defaults before export eligibility", () => {
    const mapping = createDefaultBridgeMappings().find((item) => item.category === "Show" && item.trackerField === "name")!;
    const sessions = [evidenceSession("evidence-1"), evidenceSession("evidence-2")];
    const candidate = {
      ...mapping,
      tewTable: "tblBooking",
      tewField: "Name",
      identityField: "BookingID",
      requiredDefaults: "BookingID is auto-generated; IsActive defaults to true.",
      formatNotes: "Unicode text, maximum observed length 100.",
      evidenceSessionIds: sessions.map((session) => session.id),
      confidence: "High" as const,
    };
    expect(mappingStageGate(candidate, "Export Eligible", sessions).allowed).toBe(true);
    const promoted = promoteMapping(candidate, "Export Eligible", sessions, "Two controlled comparisons matched.");
    expect(promoted.verificationStage).toBe("Export Eligible");
    expect(promoted.status).toBe("Verified");
    expect(promoted.history).toHaveLength(1);
  });

  test("blocks database export because no verified Access writer exists", () => {
    const show = configuredShow();
    const mappings = createDefaultBridgeMappings().map((mapping) => ({
      ...mapping,
      verificationStage: "Export Eligible" as const,
      status: "Verified" as const,
      confidence: "High" as const,
      tewTable: mapping.category === "Show" ? "tblBooking" : mapping.category === "Angle" ? "tblAngles" : "tblMatches",
      tewField: mapping.trackerField,
      identityField: "ID",
      requiredDefaults: "Verified defaults",
      formatNotes: "Verified format",
      evidenceSessionIds: ["evidence-1", "evidence-2"],
    }));
    const audit = buildGuardedExportAudit(show, mappings, [evidenceSession("evidence-1"), evidenceSession("evidence-2")], "test-copy.mdb", true);
    expect(audit.writingEnabled).toBe(false);
    expect(audit.writerAvailable).toBe(false);
    expect(audit.status).toBe("Eligible Pending Writer");
    expect(audit.gates.find((gate) => gate.id === "writer")?.passed).toBe(false);
  });

  test("validates an externally produced output copy through the read-only snapshot model", () => {
    const show = configuredShow();
    const snapshot: TewSnapshot = {
      fileName: "output-copy.mdb",
      fileSize: 100,
      databaseCreatedAt: "",
      importedAt: "",
      tables: [{ name: "tblBooking", rowCount: 1, columnCount: 2, columns: ["ID", "Name"], loaded: true, truncated: false }],
      workers: show.segments.flatMap((segment) => segment.workers).map((worker) => ({ id: worker.id, name: worker.name, role: worker.role, side: worker.side })),
      shows: [{ id: "show-1", name: show.name, date: show.date, rating: null, attendance: null, venue: show.venue, company: show.company, broadcast: "", matches: show.segments.filter((segment) => segment.type === "match").map((segment) => ({ id: segment.id, showId: "show-1", description: segment.title, rating: null, winner: segment.plannedWinner, matchTime: String(segment.durationMinutes), notes: "", placement: segment.section, workers: segment.workers.map((worker) => ({ id: worker.id, name: worker.name, role: worker.role, side: worker.side })) })) }],
      storylines: [],
      diagnostics: { matchedTables: {}, warnings: [], orphanMatchCount: 0, unresolvedWorkerCount: 0 },
    };
    const validation = validateRoundTrip(show, snapshot);
    expect(validation.status).toBe("Passed");
    expect(validation.checks.every((check) => check.passed)).toBe(true);
  });
});
