import type {
  ApproachAliasRecord,
  MatchAimDefinition,
  MatchApproachDefinition,
  MatchImportanceProfile,
  MentalStateDefinition,
  SourceConflictRecord,
} from "./types";

export const MATCH_APPROACHES: MatchApproachDefinition[] = [
  {
    id: "aerial-showstopper",
    name: "Aerial Showstopper",
    summary: "Dives, springboards, high-speed aerial offense.",
    formula: [
      { skill: "Aerial", weight: 0.4 },
      { skill: "Athleticism", weight: 0.3 },
      { skill: "Flashiness", weight: 0.2 },
      { skill: "Basics", weight: 0.1 },
    ],
    pace: 3,
    staminaCost: 3,
    sourceNames: ["Aerial Showstopper", "Aerial Specialist"],
    narrative: {
      styleSummary: "relied on high-flying offense",
      offensePhrase: "hitting risky dives and aerial showcases",
      sellingPhrase: "crashing hard but popping the crowd with every comeback",
      finishPhrase: "landing one last big aerial move",
    },
    sourceNotes: ["The workbook name Aerial Specialist is treated as an alias, not a second approach."],
  },
  {
    id: "big-match-performer",
    name: "Big Match Performer",
    summary: "Epic pacing, dramatic moments, rising intensity.",
    formula: [
      { skill: "Psychology", weight: 0.4 },
      { skill: "Consistency", weight: 0.3 },
      { skill: "Charisma", weight: 0.2 },
      { skill: "Stamina", weight: 0.1 },
    ],
    pace: 2,
    staminaCost: 2,
    sourceNames: ["Big Match Performer"],
    narrative: {
      styleSummary: "came alive in the big moments",
      offensePhrase: "spiking the last stretch with dramatic near falls",
      sellingPhrase: "dragging themselves up for one more huge exchange",
      finishPhrase: "closing with a huge big-match sequence",
    },
    sourceNotes: [],
  },
  {
    id: "chain-technician",
    name: "Chain Technician",
    summary: "Smooth transitions, counters, fluid mat wrestling.",
    formula: [
      { skill: "Technical", weight: 0.3 },
      { skill: "Basics", weight: 0.3 },
      { skill: "Consistency", weight: 0.2 },
      { skill: "Psychology", weight: 0.2 },
    ],
    pace: 1,
    staminaCost: 1,
    sourceNames: ["Chain Technician"],
    narrative: {
      styleSummary: "controlled the pace with crisp chain wrestling",
      offensePhrase: "chaining counters and holds together",
      sellingPhrase: "selling the struggle in each transition",
      finishPhrase: "countering into a slick technical exchange",
    },
    sourceNotes: [],
  },
  {
    id: "dirty-rulebreaker",
    name: "Dirty Rulebreaker",
    summary: "Cheating, shortcuts, and intelligent rule bending.",
    formula: [
      { skill: "Psychology", weight: 0.4 },
      { skill: "Menace", weight: 0.25 },
      { skill: "Charisma", weight: 0.2 },
      { skill: "Consistency", weight: 0.15 },
    ],
    pace: 1,
    staminaCost: 1,
    sourceNames: ["Dirty Rulebreaker"],
    narrative: null,
    sourceNotes: ["No matching narrative phrase row was present in the uploaded Top 12 phrase workbook."],
  },
  {
    id: "hardcore-daredevil",
    name: "Hardcore Daredevil",
    summary: "Weapons, chaos, and stunt bumps.",
    formula: [
      { skill: "Hardcore", weight: 0.4 },
      { skill: "Toughness", weight: 0.25 },
      { skill: "Resilience", weight: 0.2 },
      { skill: "Safety", weight: 0.15 },
    ],
    pace: 3,
    staminaCost: 3,
    sourceNames: ["Hardcore Daredevil"],
    narrative: {
      styleSummary: "brought chaos with weapons and big bumps",
      offensePhrase: "swinging chairs and throwing themselves into danger",
      sellingPhrase: "absorbing punishment in wild plunder spots",
      finishPhrase: "surviving the chaos with one last brutal spot",
    },
    sourceNotes: [],
  },
  {
    id: "heavy-striker-brawler",
    name: "Heavy Striker / Brawler",
    summary: "Scrappy strikes, fists, and wild fighting.",
    formula: [
      { skill: "Brawling", weight: 0.4 },
      { skill: "Toughness", weight: 0.25 },
      { skill: "Resilience", weight: 0.2 },
      { skill: "Menace", weight: 0.15 },
    ],
    pace: 2,
    staminaCost: 2,
    sourceNames: ["Heavy Striker / Brawler", "Heavy Striker/Brawler"],
    narrative: {
      styleSummary: "turned it into a strike-heavy brawl",
      offensePhrase: "blasting stiff strikes and wild exchanges",
      sellingPhrase: "eating and dishing out heavy shots",
      finishPhrase: "flooring their opponent with one last big shot",
    },
    sourceNotes: ["Spacing around the slash is normalized through the alias table."],
  },
  {
    id: "high-tempo-hybrid",
    name: "High Tempo Hybrid",
    summary: "Fast sequences and nonstop workrate.",
    formula: [
      { skill: "Athleticism", weight: 0.35 },
      { skill: "Stamina", weight: 0.3 },
      { skill: "Consistency", weight: 0.2 },
      { skill: "Basics", weight: 0.15 },
    ],
    pace: 3,
    staminaCost: 3,
    sourceNames: ["High Tempo Hybrid", "Workrate Machine"],
    narrative: {
      styleSummary: "kept a relentless pace",
      offensePhrase: "chaining non-stop offense and sequences",
      sellingPhrase: "showing fatigue but never really slowing down",
      finishPhrase: "outlasting their opponent in a high-tempo finish",
    },
    sourceNotes: ["Workrate Machine is retained as a narrative-library alias for High Tempo Hybrid."],
  },
  {
    id: "opportunistic-schemer",
    name: "Opportunistic Schemer",
    summary: "Picking spots and exploiting openings.",
    formula: [
      { skill: "Psychology", weight: 0.4 },
      { skill: "Basics", weight: 0.2 },
      { skill: "Charisma", weight: 0.2 },
      { skill: "Consistency", weight: 0.2 },
    ],
    pace: 1,
    staminaCost: 1,
    sourceNames: ["Opportunistic Schemer"],
    narrative: {
      styleSummary: "waited for perfect openings",
      offensePhrase: "sneaking in cheap shots and quick roll-ups",
      sellingPhrase: "bailing out whenever momentum turned",
      finishPhrase: "stealing the finish at just the right moment",
    },
    sourceNotes: [],
  },
  {
    id: "pace-controller",
    name: "Pace Controller",
    summary: "Dictates match rhythm and shifts the flow deliberately.",
    formula: [
      { skill: "Psychology", weight: 0.35 },
      { skill: "Basics", weight: 0.25 },
      { skill: "Consistency", weight: 0.25 },
      { skill: "Technical", weight: 0.15 },
    ],
    pace: 1,
    staminaCost: 1,
    sourceNames: ["Pace Controller"],
    narrative: {
      styleSummary: "dictated the tempo and structure",
      offensePhrase: "slowing things down and speeding them up at will",
      sellingPhrase: "directing the flow even while on defense",
      finishPhrase: "guiding the match into the finish they wanted",
    },
    sourceNotes: ["The source workbook contains both pace 0 and pace 1. Canonical pace 1 preserves the active Data table and Match Aims-Approaches lookup result."],
  },
  {
    id: "power-dominance",
    name: "Power Dominance",
    summary: "Strength, control, and overwhelming offense.",
    formula: [
      { skill: "Power", weight: 0.5 },
      { skill: "Toughness", weight: 0.2 },
      { skill: "Menace", weight: 0.15 },
      { skill: "Stamina", weight: 0.15 },
    ],
    pace: 2,
    staminaCost: 3,
    sourceNames: ["Power Dominance"],
    narrative: {
      styleSummary: "leaned on pure power to control the match",
      offensePhrase: "planting their opponent with big power moves",
      sellingPhrase: "staggering but always coming back with another powerhouse spot",
      finishPhrase: "hitting a huge power move in the closing stretch",
    },
    sourceNotes: [],
  },
  {
    id: "psychological-manipulator",
    name: "Psychological Manipulator",
    summary: "Mind games, taunts, and emotional disruption.",
    formula: [
      { skill: "Psychology", weight: 0.45 },
      { skill: "Charisma", weight: 0.25 },
      { skill: "Menace", weight: 0.2 },
      { skill: "Brawling", weight: 0.1 },
    ],
    pace: 1,
    staminaCost: 1,
    sourceNames: ["Psychological Manipulator"],
    narrative: {
      styleSummary: "got in their opponent’s head",
      offensePhrase: "using mind games and taunts to bait mistakes",
      sellingPhrase: "milking every reaction with smug confidence",
      finishPhrase: "capitalizing when their opponent finally snapped",
    },
    sourceNotes: [],
  },
  {
    id: "resilient-underdog",
    name: "Resilient Underdog",
    summary: "Selling damage, fiery comebacks, heart, and fight.",
    formula: [
      { skill: "Selling", weight: 0.4 },
      { skill: "Resilience", weight: 0.3 },
      { skill: "Toughness", weight: 0.2 },
      { skill: "Athleticism", weight: 0.1 },
    ],
    pace: 2,
    staminaCost: 2,
    sourceNames: ["Resilient Underdog"],
    narrative: null,
    sourceNotes: ["No matching narrative phrase row was present in the uploaded Top 12 phrase workbook."],
  },
  {
    id: "showman",
    name: "Showman",
    summary: "Crowd interaction, personality, and comedy.",
    formula: [
      { skill: "Charisma", weight: 0.45 },
      { skill: "Flashiness", weight: 0.25 },
      { skill: "Basics", weight: 0.15 },
      { skill: "Selling", weight: 0.15 },
    ],
    pace: 1,
    staminaCost: 2,
    sourceNames: ["Showman"],
    narrative: {
      styleSummary: "worked the crowd at every opportunity",
      offensePhrase: "firing up the audience and leaning into reactions",
      sellingPhrase: "selling every moment to keep the crowd hooked",
      finishPhrase: "riding the crowd energy into the final stretch",
    },
    sourceNotes: [],
  },
  {
    id: "strong-style-specialist",
    name: "Strong Style Specialist",
    summary: "Stiff strikes, fighting spirit, and high intensity.",
    formula: [
      { skill: "Puroresu", weight: 0.4 },
      { skill: "Toughness", weight: 0.3 },
      { skill: "Resilience", weight: 0.2 },
      { skill: "Consistency", weight: 0.1 },
    ],
    pace: 2,
    staminaCost: 2,
    sourceNames: ["Strong Style Specialist"],
    narrative: null,
    sourceNotes: ["No matching narrative phrase row was present in the uploaded Top 12 phrase workbook."],
  },
  {
    id: "submission-specialist",
    name: "Submission Specialist",
    summary: "Targeted limb work, holds, and technical control.",
    formula: [
      { skill: "Technical", weight: 0.4 },
      { skill: "Psychology", weight: 0.3 },
      { skill: "Basics", weight: 0.15 },
      { skill: "Toughness", weight: 0.15 },
    ],
    pace: 1,
    staminaCost: 2,
    sourceNames: ["Submission Specialist"],
    narrative: {
      styleSummary: "targeted limbs and hunted for submissions",
      offensePhrase: "grinding down limbs and chasing tap-out openings",
      sellingPhrase: "grimacing and selling the damage on every hold",
      finishPhrase: "trapping their opponent in a deep submission",
    },
    sourceNotes: [],
  },
];

export const MATCH_AIMS: MatchAimDefinition[] = [
  { id: "call-it-in-the-ring", name: "Call It in the Ring", style: "STANDARD", idealPace: 0, bestFitStyles: ["Regular", "Technician", "Technician Striker", "Technician Flyer", "Impactful"], clashStyles: ["Never Wrestles", "Hardcore", "Daredevil", "Comedy"] },
  { id: "comedy-entertainment", name: "Comedy / Entertainment", style: "COMEDY", idealPace: 3, bestFitStyles: ["Comedy", "Entertainer", "Regular", "Impactful"], clashStyles: ["Never Wrestles", "MMA Crossover", "Hardcore", "Technician"] },
  { id: "competitive-tv-match", name: "Competitive TV Match", style: "STANDARD", idealPace: 4, bestFitStyles: ["Regular", "Striker", "High Flyer", "Technician Flyer", "Impactful"], clashStyles: ["Never Wrestles", "Hardcore", "Comedy"] },
  { id: "crowd-work-showcase", name: "Crowd Work Showcase", style: "STORYTELLING", idealPace: 3, bestFitStyles: ["Entertainer", "Comedy", "Regular", "Impactful"], clashStyles: ["Never Wrestles", "MMA Crossover", "Hardcore"] },
  { id: "epic-main-event-slow-burn", name: "Epic Main Event / Slow Burn", style: "STORYTELLING", idealPace: 2, bestFitStyles: ["Technician", "Technician Striker", "Striker", "Powerhouse", "Impactful"], clashStyles: ["Comedy", "Daredevil", "Never Wrestles"] },
  { id: "elimination", name: "Elimination", style: "MULTI-MAN CHAOS", idealPace: 4, bestFitStyles: ["Regular", "Impactful", "Striker", "Powerhouse", "Technician Striker"], clashStyles: ["Never Wrestles", "Comedy"] },
  { id: "feature-match", name: "Feature Match", style: "STANDARD", idealPace: 0, bestFitStyles: [], clashStyles: [] },
  { id: "feud-grudge-match", name: "Feud/Grudge Match", style: "DRAMA", idealPace: 4, bestFitStyles: ["Brawler", "Psychopath", "Striker", "Powerhouse", "Hardcore"], clashStyles: ["Comedy", "Technician", "Never Wrestles"] },
  { id: "hardcore-war", name: "Hardcore War", style: "HARDCORE", idealPace: 6, bestFitStyles: ["Hardcore", "Psychopath", "Brawler", "Daredevil", "Powerhouse"], clashStyles: ["Technician", "MMA Crossover", "Never Wrestles"] },
  { id: "high-spots-spectacle", name: "High Spots Spectacle", style: "HIGH SPOTS", idealPace: 6, bestFitStyles: ["High Flyer", "Luchador", "Daredevil", "Technician Flyer"], clashStyles: ["Powerhouse", "Technician", "MMA Crossover", "Never Wrestles"] },
  { id: "monster-fight-hoss-battle", name: "Monster Fight / Hoss Battle", style: "POWER / HOSS", idealPace: 3, bestFitStyles: ["Powerhouse", "Brawler", "Impactful", "Striker", "Psychopath"], clashStyles: ["High Flyer", "Luchador", "Technician Flyer", "Never Wrestles"] },
  { id: "open-match", name: "Open Match", style: "STANDARD", idealPace: 0, bestFitStyles: ["Regular", "Technician", "Striker", "Impactful", "Technician Flyer"], clashStyles: ["Never Wrestles"] },
  { id: "sprint", name: "Sprint", style: "STANDARD", idealPace: 6, bestFitStyles: ["High Flyer", "Luchador", "Daredevil", "Striker", "Technician Flyer"], clashStyles: ["Powerhouse", "Technician", "Never Wrestles"] },
  { id: "storytelling-match", name: "Storytelling Match", style: "STORYTELLING", idealPace: 2, bestFitStyles: ["Technician", "Regular", "Entertainer", "Impactful", "Striker"], clashStyles: ["Never Wrestles", "Hardcore", "Daredevil"] },
  { id: "strong-style-duel", name: "Strong Style Duel", style: "STRONG STYLE", idealPace: 4, bestFitStyles: ["Striker", "Technician Striker", "Impactful", "Brawler", "MMA Crossover"], clashStyles: ["Comedy", "Luchador", "Never Wrestles"] },
  { id: "survival-chaos", name: "Survival / Chaos", style: "MULTI-MAN CHAOS", idealPace: 5, bestFitStyles: ["Psychopath", "Hardcore", "Brawler", "Powerhouse", "Daredevil"], clashStyles: ["Never Wrestles", "Technician"] },
  { id: "technical-showcase", name: "Technical Showcase", style: "TECHNICAL", idealPace: 3, bestFitStyles: ["Technician", "Technician Flyer", "Technician Striker", "MMA Crossover", "Regular"], clashStyles: ["Hardcore", "Psychopath", "Comedy", "Never Wrestles"] },
  { id: "underdog-drama", name: "Underdog Drama", style: "DRAMA", idealPace: 2, bestFitStyles: ["Regular", "High Flyer", "Luchador", "Technician", "Entertainer"], clashStyles: ["Psychopath", "Hardcore", "Never Wrestles"] },
  { id: "wild-brawl", name: "Wild Brawl", style: "BRAWL", idealPace: 5, bestFitStyles: ["Brawler", "Psychopath", "Hardcore", "Striker", "Powerhouse"], clashStyles: ["Technician", "MMA Crossover", "Never Wrestles"] },
];

export const MENTAL_STATES: MentalStateDefinition[] = [
  { id: "hot-night", name: "HOT NIGHT", modifier: 5, minimumScore: 85 },
  { id: "focused", name: "FOCUSED", modifier: 2.5, minimumScore: 70 },
  { id: "neutral", name: "NEUTRAL", modifier: 0, minimumScore: 55 },
  { id: "distracted", name: "DISTRACTED", modifier: -5, minimumScore: 40 },
  { id: "off-night", name: "OFF NIGHT", modifier: -10, minimumScore: null },
];

export const MATCH_IMPORTANCE_PROFILES: MatchImportanceProfile[] = [
  { name: "TV Open", sourceApproachCount: 2, inRingWeight: 0.7, bookingWeight: 0.3, sourceDurationBand: "5:00 or Less" },
  { name: "TV Mid-Card", sourceApproachCount: 2, inRingWeight: 0.7, bookingWeight: 0.3, sourceDurationBand: "5:00 to 15:00 Minutes" },
  { name: "PPV Opener", sourceApproachCount: 2, inRingWeight: 0.5, bookingWeight: 0.5, sourceDurationBand: "5:00 to 15:00 Minutes" },
  { name: "PPV Mid-Card", sourceApproachCount: 3, inRingWeight: 0.5, bookingWeight: 0.5, sourceDurationBand: "5:00 to 15:00 Minutes" },
  { name: "TV Feature", sourceApproachCount: 3, inRingWeight: 0.6, bookingWeight: 0.4, sourceDurationBand: "10:00 to 15:00 Minutes" },
  { name: "TV Main Event", sourceApproachCount: 3, inRingWeight: 0.6, bookingWeight: 0.4, sourceDurationBand: "15:00 to 25:00 Minutes" },
  { name: "Tournament Match", sourceApproachCount: 3, inRingWeight: 0.55, bookingWeight: 0.45, sourceDurationBand: "12:00 to 18:00 Minutes" },
  { name: "Title Match (Non-PPV)", sourceApproachCount: 3, inRingWeight: 0.4, bookingWeight: 0.6, sourceDurationBand: "10:00 to 20:00 Minutes" },
  { name: "PPV Feature", sourceApproachCount: 3, inRingWeight: 0.45, bookingWeight: 0.55, sourceDurationBand: "15:00 to 25:00 Minutes" },
  { name: "PPV Main Event", sourceApproachCount: 4, inRingWeight: 0.45, bookingWeight: 0.55, sourceDurationBand: "10:00 to 20:00 Minutes" },
  { name: "Title Match (PPV)", sourceApproachCount: 4, inRingWeight: 0.45, bookingWeight: 0.55, sourceDurationBand: "15:00 to 25:00 Minutes" },
  { name: "Non-TV Opener", sourceApproachCount: 1, inRingWeight: 0.95, bookingWeight: 0.05, sourceDurationBand: "20:00+ Minutes" },
  { name: "Non-TV Main", sourceApproachCount: 3, inRingWeight: 0.9, bookingWeight: 0.1, sourceDurationBand: "5:00 to 15:00 Minutes" },
  { name: "Squash", sourceApproachCount: 1, inRingWeight: 0.85, bookingWeight: 0.15, sourceDurationBand: "10:00 to 20:00 Minutes" },
];

export const APPROACH_ALIASES: ApproachAliasRecord[] = [
  { sourceName: "Aerial Showstopper", normalizedName: "aerial showstopper", canonicalId: "aerial-showstopper", status: "canonical", note: "Canonical name from the approach-definition document." },
  { sourceName: "Aerial Specialist", normalizedName: "aerial specialist", canonicalId: "aerial-showstopper", status: "alias", note: "Workbook alias for Aerial Showstopper." },
  { sourceName: "Heavy Striker / Brawler", normalizedName: "heavy striker brawler", canonicalId: "heavy-striker-brawler", status: "canonical", note: "Canonical punctuation." },
  { sourceName: "Heavy Striker/Brawler", normalizedName: "heavy striker brawler", canonicalId: "heavy-striker-brawler", status: "alias", note: "Workbook punctuation alias." },
  { sourceName: "High Tempo Hybrid", normalizedName: "high tempo hybrid", canonicalId: "high-tempo-hybrid", status: "canonical", note: "Canonical name from the approach-definition document." },
  { sourceName: "Workrate Machine", normalizedName: "workrate machine", canonicalId: "high-tempo-hybrid", status: "alias", note: "Phrase-library name for High Tempo Hybrid." },
  { sourceName: "Counter Specialist", normalizedName: "counter specialist", canonicalId: null, status: "legacy-unmapped", note: "Present in the match workbook but absent from the fifteen-approach definition document. Preserved for manual review." },
  { sourceName: "Ring General", normalizedName: "ring general", canonicalId: null, status: "legacy-unmapped", note: "Present in the match workbook but absent from the fifteen-approach definition document. Preserved for manual review." },
];

export const SOURCE_CONFLICTS: SourceConflictRecord[] = [
  {
    id: "pace-controller-pace",
    area: "Approach pace",
    sourceValues: ["Match Tables: 0", "Data / Match Aims-Approaches: 1"],
    canonicalValue: "1",
    resolution: "Use the active Data-table lookup value while retaining the conflicting Match Tables value in diagnostics.",
  },
  {
    id: "importance-approach-count",
    area: "Approach slot count",
    sourceValues: ["Legacy importance profiles contain their own approach counts", "Approved duration rule determines 1-4 approach slots"],
    canonicalValue: "Duration-based slots",
    resolution: "Preserve legacy counts for parity and comparison, but the new engine uses the approved duration boundaries as its authority.",
  },
];
