import type { MatchAimId, MatchApproachId, WrestlerSkill, WrestlerStyleDefinition } from "./types";

export const MATCH_ENGINE_SKILLS: WrestlerSkill[] = [
  "Aerial",
  "Athleticism",
  "Basics",
  "Brawling",
  "Charisma",
  "Consistency",
  "Flashiness",
  "Hardcore",
  "Menace",
  "Power",
  "Psychology",
  "Puroresu",
  "Resilience",
  "Safety",
  "Selling",
  "Stamina",
  "Technical",
  "Toughness",
];

export const WRESTLER_STYLES: WrestlerStyleDefinition[] = [
  {
    id: "all-rounder",
    name: "All-Rounder",
    summary: "Balanced fundamentals, moderate athleticism, and adaptable psychology.",
    approachBoosts: ["pace-controller", "counter-specialist"],
    aimBoosts: ["technical-showcase", "competitive-tv-match"],
    aimStyleNames: ["Regular"],
  },
  {
    id: "brawler",
    name: "Brawler",
    summary: "Fists, scrappy exchanges, intensity, and controlled chaos.",
    approachBoosts: ["heavy-striker-brawler"],
    aimBoosts: ["wild-brawl", "strong-style-duel"],
    aimStyleNames: ["Striker"],
  },
  {
    id: "comedy-performer",
    name: "Comedy Performer",
    summary: "Personality, timing, reactions, and crowd interaction.",
    approachBoosts: ["showman"],
    aimBoosts: ["comedy-entertainment", "crowd-work-showcase"],
    aimStyleNames: ["Comedy"],
  },
  {
    id: "daredevil",
    name: "Daredevil",
    summary: "Stunt bumps, wild offense, risk-taking, and spectacle.",
    approachBoosts: ["hardcore-daredevil"],
    aimBoosts: ["high-spots-spectacle", "wild-brawl"],
    aimStyleNames: ["Daredevil", "Hardcore"],
  },
  {
    id: "entertainer",
    name: "Entertainer",
    summary: "Character-first showmanship with broad crowd-friendly offense.",
    approachBoosts: ["showman"],
    aimBoosts: ["crowd-work-showcase", "feature-match"],
    aimStyleNames: ["Entertainer"],
  },
  {
    id: "high-flyer",
    name: "High Flyer",
    summary: "High-speed aerial offense, rope work, and explosive dives.",
    approachBoosts: ["aerial-showstopper"],
    aimBoosts: ["high-spots-spectacle", "sprint"],
    aimStyleNames: ["High Flyer"],
  },
  {
    id: "heavyweight-powerhouse",
    name: "Heavyweight Powerhouse",
    summary: "Strength, slower control, intimidation, and domination.",
    approachBoosts: ["power-dominance"],
    aimBoosts: ["monster-fight-hoss-battle", "epic-main-event-slow-burn"],
    aimStyleNames: ["Powerhouse"],
  },
  {
    id: "hybrid-technician-flyer",
    name: "Hybrid Technician-Flyer",
    summary: "Chain wrestling and aerial sequences connected by smooth transitions.",
    approachBoosts: ["chain-technician", "aerial-showstopper", "high-tempo-hybrid"],
    aimBoosts: ["technical-showcase", "high-spots-spectacle"],
    aimStyleNames: ["Technician Flyer"],
  },
  {
    id: "hybrid-technician-striker",
    name: "Hybrid Technician-Striker",
    summary: "Mat grappling mixed with sharp strikes and submission threats.",
    approachBoosts: ["chain-technician", "strong-style-specialist"],
    aimBoosts: ["technical-showcase", "strong-style-duel"],
    aimStyleNames: ["Technician Striker"],
  },
  {
    id: "impact-striker",
    name: "Impact Striker",
    summary: "Explosive, sharp, high-impact offense without relying on a wild brawl.",
    approachBoosts: ["strong-style-specialist", "high-tempo-hybrid"],
    aimBoosts: ["competitive-tv-match", "strong-style-duel"],
    aimStyleNames: ["Impactful", "Striker"],
  },
  {
    id: "luchador",
    name: "Luchador",
    summary: "Rope-running rhythm, fluid sequences, speed, and aerial creativity.",
    approachBoosts: ["aerial-showstopper", "high-tempo-hybrid"],
    aimBoosts: ["high-spots-spectacle", "sprint"],
    aimStyleNames: ["High Flyer", "Technician Flyer"],
  },
  {
    id: "mma-crossover",
    name: "MMA Crossover",
    summary: "Submissions, strikes, clinch work, and credible grappling.",
    approachBoosts: ["submission-specialist", "strong-style-specialist"],
    aimBoosts: ["technical-showcase", "strong-style-duel"],
    aimStyleNames: ["MMA Crossover"],
  },
  {
    id: "pure-technician",
    name: "Pure Technician",
    summary: "Chain wrestling, grappling, limb work, and submissions.",
    approachBoosts: ["chain-technician", "counter-specialist", "submission-specialist"],
    aimBoosts: ["technical-showcase", "call-it-in-the-ring"],
    aimStyleNames: ["Technician"],
  },
  {
    id: "resilient-underdog",
    name: "Resilient Underdog",
    summary: "Selling, sympathetic comebacks, heart, and survival.",
    approachBoosts: ["resilient-underdog"],
    aimBoosts: ["underdog-drama", "storytelling-match"],
    aimStyleNames: ["Regular"],
  },
  {
    id: "show-stealer-workhorse",
    name: "Show-Stealer / Workhorse",
    summary: "High workrate, long matches, smooth execution, and escalating pace.",
    approachBoosts: ["high-tempo-hybrid", "big-match-performer"],
    aimBoosts: ["sprint", "high-spots-spectacle", "feature-match"],
    aimStyleNames: ["Impactful", "Regular"],
  },
];

// Transparent Phase 4C2 AI hints. These connect the source approach descriptions
// to the selected match aim, but are not presented as workbook formulas.
export const AIM_APPROACH_HINTS: Record<MatchAimId, MatchApproachId[]> = {
  "call-it-in-the-ring": ["pace-controller", "counter-specialist", "chain-technician", "opportunistic-schemer", "big-match-performer"],
  "comedy-entertainment": ["showman", "psychological-manipulator", "dirty-rulebreaker"],
  "competitive-tv-match": ["high-tempo-hybrid", "counter-specialist", "chain-technician", "strong-style-specialist", "aerial-showstopper"],
  "crowd-work-showcase": ["showman", "psychological-manipulator", "big-match-performer"],
  "epic-main-event-slow-burn": ["big-match-performer", "pace-controller", "resilient-underdog", "power-dominance"],
  elimination: ["opportunistic-schemer", "resilient-underdog", "power-dominance", "high-tempo-hybrid"],
  "feature-match": ["big-match-performer", "high-tempo-hybrid", "showman"],
  "feud-grudge-match": ["heavy-striker-brawler", "psychological-manipulator", "dirty-rulebreaker", "resilient-underdog"],
  "hardcore-war": ["hardcore-daredevil", "heavy-striker-brawler", "resilient-underdog"],
  "high-spots-spectacle": ["aerial-showstopper", "high-tempo-hybrid", "hardcore-daredevil"],
  "monster-fight-hoss-battle": ["power-dominance", "heavy-striker-brawler", "resilient-underdog"],
  "open-match": [],
  sprint: ["high-tempo-hybrid", "aerial-showstopper", "strong-style-specialist"],
  "storytelling-match": ["big-match-performer", "pace-controller", "resilient-underdog", "psychological-manipulator"],
  "strong-style-duel": ["strong-style-specialist", "heavy-striker-brawler", "resilient-underdog"],
  "survival-chaos": ["resilient-underdog", "opportunistic-schemer", "hardcore-daredevil"],
  "technical-showcase": ["chain-technician", "counter-specialist", "submission-specialist", "pace-controller"],
  "underdog-drama": ["resilient-underdog", "big-match-performer", "psychological-manipulator"],
  "wild-brawl": ["heavy-striker-brawler", "hardcore-daredevil", "dirty-rulebreaker"],
};
