import type { PlannedShow } from "../planner/types";
import type { TewResearchSnapshot, TewResearchTable, TewSnapshot } from "../tew/types";
import { buildBridgeDryRun } from "./model";
import type {
  BridgeFieldMapping,
  BridgeMappingHistoryEntry,
  BridgeMappingVerificationStage,
  GuardedExportAudit,
  GuardedExportGate,
  RawEvidenceSession,
  RawFieldChange,
  RawRowChange,
  RawTableEvidence,
  RoundTripValidation,
} from "./types";

function id(prefix: string): string {
  return typeof crypto !== "undefined" && typeof crypto.randomUUID === "function"
    ? crypto.randomUUID()
    : `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
}

export function verificationStage(mapping: BridgeFieldMapping): BridgeMappingVerificationStage {
  if (mapping.verificationStage) return mapping.verificationStage;
  if (mapping.status === "Verified") return "Verified";
  if (mapping.status === "Unsupported") return "Unsupported";
  return "Candidate";
}

function tableByName(snapshot: TewResearchSnapshot, tableName: string): TewResearchTable | undefined {
  const normalized = tableName.toLowerCase();
  return snapshot.tables.find((table) => table.name.toLowerCase() === normalized);
}

function rowKey(row: Record<string, string>, identityField: string): string {
  if (identityField && row[identityField]) return row[identityField];
  return Object.entries(row).sort(([left], [right]) => left.localeCompare(right)).map(([key, value]) => `${key}=${value}`).join("|");
}

function fieldChanges(beforeRow: Record<string, string>, afterRow: Record<string, string>): RawFieldChange[] {
  const fields = new Set([...Object.keys(beforeRow), ...Object.keys(afterRow)]);
  return [...fields].sort().flatMap((field) => {
    const beforeValue = beforeRow[field] ?? "";
    const afterValue = afterRow[field] ?? "";
    return beforeValue === afterValue ? [] : [{ field, beforeValue, afterValue }];
  });
}

function compareRawTable(before: TewResearchTable | undefined, after: TewResearchTable | undefined, identityField: string): RawTableEvidence {
  const tableName = after?.name ?? before?.name ?? "Unknown table";
  const beforeRows = before?.rows ?? [];
  const afterRows = after?.rows ?? [];
  const beforeByKey = new Map(beforeRows.map((row) => [rowKey(row, identityField), row]));
  const afterByKey = new Map(afterRows.map((row) => [rowKey(row, identityField), row]));
  const rowChanges: RawRowChange[] = [];

  for (const [key, afterRow] of afterByKey) {
    const beforeRow = beforeByKey.get(key);
    if (!beforeRow) {
      rowChanges.push({ tableName, identityField, identityValue: key, changeType: "Inserted", fieldChanges: [], beforeRow: null, afterRow });
      continue;
    }
    const changes = fieldChanges(beforeRow, afterRow);
    if (changes.length > 0) rowChanges.push({ tableName, identityField, identityValue: key, changeType: "Changed", fieldChanges: changes, beforeRow, afterRow });
  }
  for (const [key, beforeRow] of beforeByKey) {
    if (!afterByKey.has(key)) rowChanges.push({ tableName, identityField, identityValue: key, changeType: "Removed", fieldChanges: [], beforeRow, afterRow: null });
  }

  const inserted = rowChanges.filter((row) => row.changeType === "Inserted");
  const changed = rowChanges.filter((row) => row.changeType === "Changed");
  const generatedCandidates = new Map<string, number>();
  for (const row of [...inserted, ...changed]) {
    for (const change of row.fieldChanges) {
      if (!change.beforeValue && change.afterValue) generatedCandidates.set(change.field, (generatedCandidates.get(change.field) ?? 0) + 1);
    }
    if (row.changeType === "Inserted" && row.afterRow) {
      for (const [field, value] of Object.entries(row.afterRow)) {
        if (value && /id|key|uid|date|time|created|modified|order|number/i.test(field)) generatedCandidates.set(field, (generatedCandidates.get(field) ?? 0) + 1);
      }
    }
  }

  return {
    tableName,
    identityField,
    beforeRowCount: before?.rowCount ?? 0,
    afterRowCount: after?.rowCount ?? 0,
    sampledBeforeRows: before?.sampledRows ?? 0,
    sampledAfterRows: after?.sampledRows ?? 0,
    insertedCount: inserted.length,
    removedCount: rowChanges.filter((row) => row.changeType === "Removed").length,
    changedCount: changed.length,
    autoGeneratedFields: [...generatedCandidates.entries()].filter(([, count]) => count > 0).sort((left, right) => right[1] - left[1]).map(([field]) => field),
    rowChanges: rowChanges.slice(0, 250),
    notes: identityField
      ? `Rows matched by ${identityField}. Review repeated sessions before treating this as proof of a relationship.`
      : "No identity field was confirmed. Exact row signatures were used, so changed rows may appear as one removal and one insertion.",
  };
}

export function buildRawEvidenceSession(
  comparisonReportId: string,
  before: TewResearchSnapshot,
  after: TewResearchSnapshot,
  selectedTables: string[],
  identityFields: Record<string, string>,
): RawEvidenceSession {
  const tableEvidence = selectedTables.map((tableName) => compareRawTable(
    tableByName(before, tableName),
    tableByName(after, tableName),
    identityFields[tableName] ?? tableByName(after, tableName)?.identityCandidates[0] ?? tableByName(before, tableName)?.identityCandidates[0] ?? "",
  ));
  const changedTables = tableEvidence.filter((table) => table.insertedCount + table.removedCount + table.changedCount > 0).length;
  return {
    id: id("raw-evidence"),
    comparisonReportId,
    createdAt: new Date().toISOString(),
    beforeFileName: before.fileName,
    afterFileName: after.fileName,
    selectedTables,
    identityFields: Object.fromEntries(tableEvidence.map((table) => [table.tableName, table.identityField])),
    tableEvidence,
    conclusion: `${changedTables} of ${tableEvidence.length} researched tables contained sampled row-level differences. This is evidence for mapping research, not permission to write.`,
  };
}

export interface MappingGateResult {
  allowed: boolean;
  reasons: string[];
}

export function mappingStageGate(
  mapping: BridgeFieldMapping,
  targetStage: BridgeMappingVerificationStage,
  evidenceSessions: RawEvidenceSession[],
): MappingGateResult {
  if (targetStage === "Candidate" || targetStage === "Unsupported") return { allowed: true, reasons: [] };
  const linkedIds = mapping.evidenceSessionIds ?? [];
  const linked = evidenceSessions.filter((session) => linkedIds.includes(session.id));
  const supporting = linked.filter((session) => session.tableEvidence.some((table) =>
    table.tableName.toLowerCase() === mapping.tewTable.toLowerCase()
    && table.rowChanges.some((row) => !mapping.tewField || row.fieldChanges.some((field) => field.field.toLowerCase() === mapping.tewField.toLowerCase()) || row.afterRow?.[mapping.tewField] !== undefined),
  ));
  const reasons: string[] = [];
  if (!mapping.tewTable.trim()) reasons.push("A TEW table is required.");
  if (!mapping.tewField.trim()) reasons.push("A TEW field is required.");
  if (supporting.length < 1) reasons.push("At least one linked raw-evidence session must support the table and field.");
  if ((targetStage === "Verified" || targetStage === "Export Eligible") && supporting.length < 2) reasons.push("Verification requires evidence from at least two separate controlled comparisons.");
  if ((targetStage === "Verified" || targetStage === "Export Eligible") && !(mapping.identityField ?? "").trim()) reasons.push("A confirmed record identity field is required.");
  if (targetStage === "Export Eligible" && mapping.confidence !== "High") reasons.push("Export eligibility requires High confidence.");
  if (targetStage === "Export Eligible" && !(mapping.formatNotes ?? "").trim()) reasons.push("Document the TEW value format before export eligibility.");
  if (targetStage === "Export Eligible" && !(mapping.requiredDefaults ?? "").trim()) reasons.push("Document TEW-required default values before export eligibility.");
  return { allowed: reasons.length === 0, reasons };
}

export function promoteMapping(
  mapping: BridgeFieldMapping,
  targetStage: BridgeMappingVerificationStage,
  evidenceSessions: RawEvidenceSession[],
  reason: string,
): BridgeFieldMapping {
  const gate = mappingStageGate(mapping, targetStage, evidenceSessions);
  if (!gate.allowed) throw new Error(gate.reasons.join(" "));
  const fromStage = verificationStage(mapping);
  const historyEntry: BridgeMappingHistoryEntry = { id: id("mapping-history"), changedAt: new Date().toISOString(), fromStage, toStage: targetStage, reason: reason.trim() || "Stage changed after evidence review." };
  return {
    ...mapping,
    verificationStage: targetStage,
    status: targetStage === "Unsupported" ? "Unsupported" : targetStage === "Verified" || targetStage === "Export Eligible" ? "Verified" : "Candidate",
    history: [...(mapping.history ?? []), historyEntry],
    updatedAt: historyEntry.changedAt,
  };
}

function gate(idValue: string, label: string, passed: boolean, detail: string): GuardedExportGate {
  return { id: idValue, label, passed, detail };
}

export function buildGuardedExportAudit(
  show: PlannedShow,
  mappings: BridgeFieldMapping[],
  evidenceSessions: RawEvidenceSession[],
  sourceFileName: string,
  sourceCopyConfirmed: boolean,
): GuardedExportAudit {
  const dryRun = buildBridgeDryRun(show, mappings);
  const requiredMappings = mappings.filter((mapping) => ["Show", "Match", "Angle"].includes(mapping.category));
  const exportEligible = requiredMappings.filter((mapping) => verificationStage(mapping) === "Export Eligible");
  const linkedEvidence = new Set(exportEligible.flatMap((mapping) => mapping.evidenceSessionIds ?? []));
  const allWorkersResolved = show.segments.every((segment) => segment.workers.every((worker) => worker.source === "tew" && Boolean(worker.id)));
  const allRequiredValuesPresent = Boolean(show.name.trim() && show.date.trim()) && show.segments.length > 0 && show.segments.every((segment) =>
    Boolean(segment.title.trim())
    && segment.durationMinutes > 0
    && segment.workers.length > 0
    && (segment.type === "angle" || Boolean(segment.matchType.trim())),
  );
  const mappingsComplete = requiredMappings.length > 0 && exportEligible.length === requiredMappings.length;
  const evidenceAvailable = exportEligible.length > 0 && [...linkedEvidence].every((sessionId) => evidenceSessions.some((session) => session.id === sessionId));
  const gates: GuardedExportGate[] = [
    gate("source-copy", "A copied source database is explicitly confirmed", sourceCopyConfirmed && Boolean(sourceFileName), sourceCopyConfirmed ? sourceFileName || "Source copy selected" : "Confirm that the selected file is a disposable copy, never the only live save."),
    gate("automatic-backup", "A second automatic backup is required", true, "Any future writer must create a second backup before producing an output copy."),
    gate("mapping-eligibility", "Every required operation has an Export Eligible mapping", mappingsComplete, `${exportEligible.length} of ${requiredMappings.length} required mappings are Export Eligible.`),
    gate("evidence", "All exporter mappings retain linked raw evidence", evidenceAvailable, evidenceAvailable ? `${linkedEvidence.size} evidence sessions linked.` : "Exporter mappings require retained raw evidence."),
    gate("ids", "Every participant resolves to a TEW identifier", allWorkersResolved, allWorkersResolved ? "All planned workers are TEW-linked." : "One or more planned workers are manual or lack a TEW identifier."),
    gate("values", "Required tracker values are present", allRequiredValuesPresent, allRequiredValuesPresent ? "Show identity and essential segment values are complete." : "Complete show identity, segment title, duration, participants, and match type."),
    gate("writer", "A verified Microsoft Access write engine is available", false, "The browser dependency is read-only. No verified Access writer is installed, so database output is blocked."),
  ];
  const blockers = gates.filter((item) => !item.passed).map((item) => item.detail);
  const proposedOutputFileName = sourceFileName ? sourceFileName.replace(/\.(mdb|accdb)$/i, "-tracker-output.$1") : `${show.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-tracker-output.mdb`;
  return {
    id: id("export-audit"),
    showId: show.id,
    showName: show.name,
    createdAt: new Date().toISOString(),
    sourceFileName,
    proposedOutputFileName,
    sourceCopyConfirmed,
    writerAvailable: false,
    writingEnabled: false,
    status: blockers.length === 1 && blockers[0].includes("write engine") ? "Eligible Pending Writer" : "Blocked",
    gates,
    dryRun,
    blockers,
    auditNotes: [
      "The prototype never modifies the selected source file.",
      "No output database is produced while the Access writer gate is blocked.",
      "Match approaches and generated narratives remain companion data unless a verified TEW storage location is proven.",
    ],
    roundTripValidation: { validatedAt: "", outputFileName: "", status: "Not Run", checks: [] },
  };
}

function normalize(value: string): string {
  return value.trim().toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

export function validateRoundTrip(show: PlannedShow, output: TewSnapshot): RoundTripValidation {
  const matchedShow = output.shows.find((candidate) => normalize(candidate.name) === normalize(show.name) && (!show.date || !candidate.date || candidate.date === show.date));
  const expectedMatches = show.segments.filter((segment) => segment.type === "match");
  const actualMatches = matchedShow?.matches ?? [];
  const checks: GuardedExportGate[] = [
    gate("readable", "Output database remains readable", output.tables.length > 0, `${output.tables.length} tables inspected.`),
    gate("show", "Expected show record exists", Boolean(matchedShow), matchedShow ? `${matchedShow.name} matched.` : `${show.name} was not found.`),
    gate("running-order", "Expected match count is present", Boolean(matchedShow) && actualMatches.length >= expectedMatches.length, `${actualMatches.length} actual matches for ${expectedMatches.length} planned matches.`),
    gate("participants", "TEW-linked participants remain resolvable", expectedMatches.every((segment) => segment.workers.every((worker) => output.workers.some((candidate) => candidate.id === worker.id || normalize(candidate.name) === normalize(worker.name)))), "Every planned TEW-linked worker must resolve in the output copy."),
  ];
  const passed = checks.every((item) => item.passed);
  return { validatedAt: new Date().toISOString(), outputFileName: output.fileName, status: passed ? "Passed" : "Failed", checks };
}
